version: '3.1'

networks:
  evidence-handler-network:
    driver: bridge


services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION_STRING=mongodb://root:password@mongo:27017/
    networks:
      - evidence-handler-network
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - evidence-handler-network
